# Generated by Django 3.0.3 on 2020-02-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_disability_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='disability',
            name='myurl',
            field=models.URLField(default='mute.html/'),
        ),
    ]
