# Generated by Django 3.0.3 on 2020-02-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_disability_myurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='photo',
            field=models.ImageField(default='blindkid.jpg', upload_to='InternalPics/'),
        ),
    ]
