# Generated by Django 3.0.3 on 2020-02-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_subject_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disability',
            name='audio',
            field=models.FileField(default='mute.mp3', upload_to='media/'),
        ),
    ]
